### ISSUE TITLE
Missing in-cog credit

### ISSUE THREAD

**Issue by Crossedfall** [optimumtact/orangescogs#28]
Heya,

I noticed that my authorship was removed from the tgdb cog, which was built upon my getnotes cog. The line in the README is appreciated, but that isn't read by Redbot nor the various cog scrapers. Can you please re-add me as an additional author to maintain credit? Thank you.

https://github.com/optimumtact/orangescogs/blob/e8a7d291801c14d7a5e7d65a1058496f422e1e6e/tgdb/info.json#L2

https://github.com/optimumtact/orangescogs/blob/e8a7d291801c14d7a5e7d65a1058496f422e1e6e/tgdb/tgdb.py#L22

**Comment by Crossedfall** [comment]
You also need to add a copyright line within the MIT license for my work or add a separate copy of the MIT license within the tgdb cog's folder specifically attributed to me. As I have not withdrawn my rights.

https://github.com/optimumtact/orangescogs/blob/e8a7d291801c14d7a5e7d65a1058496f422e1e6e/LICENSE#L3

**Comment by optimumtact** [comment]
i'll do these sometime today

**Comment by optimumtact** [comment]
does `__author__` support a list?

**Comment by optimumtact** [comment]
should be good now, I added your copyright back to the main license, let me know if you'd prefer an independent MIT license in the tgdb submodule.

**Comment by Crossedfall** [comment]
All good by me! Thank you. ❤️
